// default package
// Generated 29/11/2017 09:38:28 AM by Hibernate Tools 5.2.6.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private String nombre;
	

	public Usuario() {
	}

	public Usuario(String nombre, String correo, String contrasenia, String cel) {
		this.nombre = nombre;
		
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
